### ISSUE TITLE
大佬还会做别的渠道的包嘛

### ISSUE THREAD

**Issue by micro152** [liusj5257/azurlane_anti_name#10]

**Comment by dark-knifes** [comment]
根据手动教程自行修改即可

**Comment by micro152** [comment]
[image: image.png]
大佬请问apk中的lib文件夹路径是什么

夜刃 ***@***.***> 于2023年3月25日周六 09:10写道：

**Comment by dark-knifes** [comment]
com.bilibili.blhx.xxxxx/lib

**Comment by micro152** [comment]
抱歉问了个蠢问题😂

莲梅莉 ***@***.***> 于2023年3月25日周六 12:12写道：
