### ISSUE TITLE
请问如何和隔壁的Perseus一起用

### ISSUE THREAD

**Issue by Trastice** [liusj5257/azurlane_anti_name#13]
每次只有前一个生效
:(

**Comment by dark-knifes** [comment]
手动修改即可 perseus 放在反和谐前

**Comment by Trastice** [comment]
那perseus生效 改名字就不生效了
反过来改名字生效 perseus就不生效了
:(

**Comment by dark-knifes** [comment]
> 那perseus生效 改名字就不生效了 反过来改名字生效 perseus就不生效了 :(

我亲测有效，只需这样即可
![Screenshot_2023-03-25-10-44-05-981_bin mt plus-edit](https://user-images.githubusercontent.com/75507531/227682782-e821a27a-5d7a-46cd-a44a-570f16ca0015.jpg)

**Comment by Trastice** [comment]
试了好多次还是不行，代码都一摸一样，有没有同时生效的b服包给一下（

**Comment by dark-knifes** [comment]
> 试了好多次还是不行，代码都一摸一样，有没有同时生效的b服包给一下（

还有前面的18行两端代码

**Comment by Trastice** [comment]
> 

都有的 还是只有第一个生效

**Comment by Trastice** [comment]
两个库都有导入提示 但还是只能第一个生效 太气了 
X(

**Comment by dark-knifes** [comment]
> 两个库都有导入提示 但还是只能第一个生效 太气了 X(

有没有enjoy the feet 的提示？

**Comment by Trastice** [comment]
有enjoy the feet提示 和原名 但是不能换皮肤 皮肤情况就跟原版一样

**Comment by dark-knifes** [comment]
> 有enjoy the feet提示 和原名 但是不能换皮肤 皮肤情况就跟原版一样
配置没改，**大聪明**

**Comment by Trastice** [comment]
perseus都用好久了肯定改了的啊

**Comment by Trastice** [comment]
![image](https://user-images.githubusercontent.com/65207717/227702699-e675df5d-119b-4d3b-9f26-d33dd55eea4e.png)
![image](https://user-images.githubusercontent.com/65207717/227702712-d5d90c12-a97b-4f0d-bc72-b5ccd67d2823.png)
![image](https://user-images.githubusercontent.com/65207717/227702728-a6d6c94f-167a-45fc-b1a9-00cd360ff940.png)

**Comment by dark-knifes** [comment]
不知道:)

**Comment by Trastice** [comment]
:(

**Comment by dark-knifes** [comment]
:) 
![Screenshot_2023-03-25-15-14-22-141_com bilibili blhx huawei-edit](https://user-images.githubusercontent.com/75507531/227703033-d768255a-90d7-413f-af4e-d3f1cb28a506.jpg)

**Comment by dark-knifes** [comment]
[classes.txt](https://github.com/liusj5257/azurlane_anti_name/files/11068281/classes.txt)
试试这个我改好的classes.dex  下载好后缀改成.dex 拖到安装包里替换

**Comment by Trastice** [comment]
b服dex分开的 unity在3里 合并超过字节了 我再想想办法
![image](https://user-images.githubusercontent.com/65207717/227704371-dd3a17f3-e775-4cc0-b1d8-54e800d07f66.png)

**Comment by Trastice** [comment]
有办法了记得喊我(
哼哼啊啊啊啊啊啊啊

**Comment by Trastice** [comment]
![image](https://user-images.githubusercontent.com/65207717/227754462-44d62fa5-d855-48c6-9547-4d6cfe80108f.png)
官方后门文件
都为true perseus生效改名字无效
有false 改名字生效perseus不生效
是不是代码有点小问题

**Comment by IA20201** [comment]
> 

老哥你可以试试在编译好的反和谐包上加上Perseus库，我b服生效了
![Screenshot_2023-03-26-15-07-03-624_com bilibili azurlane](https://user-images.githubusercontent.com/75969201/227760846-a54cef89-0f8c-4789-bd6e-f97c27c371f2.jpg)

**Comment by Trastice** [comment]
> > 
> 
> 老哥你可以试试在编译好的反和谐包上加上Perseus库，我b服生效了 ![Screenshot_2023-03-26-15-07-03-624_com bilibili azurlane](https://user-images.githubusercontent.com/75969201/227760846-a54cef89-0f8c-4789-bd6e-f97c27c371f2.jpg)

可否把apk包或者三个classes.dex发一下让我康康

**Comment by IA20201** [comment]
> > > 
> > 
> > 
> > 老哥你可以试试在编译好的反和谐包上加上Perseus库，我b服生效了 ![Screenshot_2023-03-26-15-07-03-624_com bilibili azurlane](https://user-images.githubusercontent.com/75969201/227760846-a54cef89-0f8c-4789-bd6e-f97c27c371f2.jpg)
> 
> 可否把apk包或者三个classes.dex发一下让我康康

https://www.aliyundrive.com/s/JwbUr7z7mny

**Comment by IA20201** [comment]
> > > 
> > 
> > 
> > 老哥你可以试试在编译好的反和谐包上加上Perseus库，我b服生效了 ![Screenshot_2023-03-26-15-07-03-624_com bilibili azurlane](https://user-images.githubusercontent.com/75969201/227760846-a54cef89-0f8c-4789-bd6e-f97c27c371f2.jpg)
> 
> 可否把apk包或者三个classes.dex发一下让我康康

但我把做好的包放到模拟器上只能生效一个库（

**Comment by Trastice** [comment]
> 但我把做好的包放到模拟器上只能生效一个库（
草原来是模拟器！ 可恶的模拟器

**Comment by IA20201** [comment]
> > 但我把做好的包放到模拟器上只能生效一个库（
> > 草原来是模拟器！ 可恶的模拟器

能交流一下吗，邮箱jhdhhu@163.com

**Comment by Trastice** [comment]
应该是类名或者啥东西撞了吧，等一个合并:P

**Comment by jinseweixin** [comment]
佬们有新的安装包吗
