### ISSUE TITLE
大佬，小米服的按教程来换直接闪退是为啥啊

### ISSUE THREAD

**Issue by lan123231** [liusj5257/azurlane_anti_name#14]

**Comment by dark-knifes** [comment]
细说

**Comment by dark-knifes** [comment]
或者b站视频里有搓好的小米服

**Comment by lan123231** [comment]
就是直接闪退报错，然后看应用信息里面也没版本号

**Comment by lan123231** [comment]
就是直接闪退但安装那些都是可以通过的，并且模拟器和手机都装不上

**Comment by dark-knifes** [comment]
是不是lib没有放进去

**Comment by lan123231** [comment]
![E3DAZ)M3TZIJ5290T@WLX69](https://user-images.githubusercontent.com/128900138/227715349-076cf2f3-b37f-4e5e-8934-325584ed45a4.jpg)

**Comment by lan123231** [comment]
![E3DAZ)M3TZIJ5290T@WLX69](https://user-images.githubusercontent.com/128900138/227715403-a641c092-0263-4d06-8f86-9846aeb158d9.jpg)

**Comment by dark-knifes** [comment]
6
