### ISSUE TITLE
换装预览功能回归的可能性？

### ISSUE THREAD

**Issue by WKyouka** [liusj5257/azurlane_anti_name#19]
某次和谐后，角色详情中的换装预览被和谐了，无法查看没有购买的皮肤
这个功能是否有回归的方法？

![20230330213131](https://user-images.githubusercontent.com/69430239/228852610-df2e7e03-2afa-4e1b-8093-94abfcaf9fb2.png)

**Comment by liusj5257** [comment]
可以改个变量就回来了，但这个功能重要么

**Comment by WKyouka** [comment]
> 可以改个变量就回来了，但这个功能重要么

重要性确实不高，我单纯想着功能全部复原的可行性hhh

**Comment by E5sixuqi** [comment]
> 可以改个变量就回来了，但这个功能重要么

希望大佬能改一下

**Comment by Meteor-Sage** [comment]
感觉很重要，能预览皮肤还是挺有用的

**Comment by liusj5257** [comment]
done
