### ISSUE TITLE
小米手机安装失败了

### ISSUE THREAD

**Issue by micro152** [liusj5257/azurlane_anti_name#22]
模拟器倒是没问题，安装后能用，小米手机倒是安装失败了
![Screenshot_2023-04-01-21-46-19-411_com miui packageinstaller](https://user-images.githubusercontent.com/128870741/229293096-080dfe18-a224-4abd-a494-c579cbdccfa0.jpg)

**Comment by dark-knifes** [comment]
手动修改的还是下载release的

**Comment by micro152** [comment]
> 手动修改的还是下载release的

手动修改的，这是小米服

**Comment by wuqy-2000** [comment]
没有签名

**Comment by micro152** [comment]
> 没有签名
解决了，谢谢大佬
