### ISSUE TITLE
小米安装报毒

### ISSUE THREAD

**Issue by EasyRain** [liusj5257/azurlane_anti_name#23]
![PPGHP5BVN N}DDE7B8Q071M](https://user-images.githubusercontent.com/46843500/229340368-d12faa93-8515-4832-bf9c-b12c8d200680.jpg)

**Comment by IA20201** [comment]
https://github.com/HuanCheng65/TiebaLite/issues/44#issue-849296125误报吧

**Comment by EasyRain** [comment]
> [https://github.com/HuanCheng65/TiebaLite/issues/44#issue-849296125 误报吧](https://github.com/HuanCheng65/TiebaLite/issues/44#issue-849296125%E8%AF%AF%E6%8A%A5%E5%90%A7)

这次更新文件后启动游戏会弹出一个提示“免费 自由 风险未知 bilibili_NeatVest”，不知道是不是这个的原因

**Comment by wuqy-2000** [comment]
签名导致的报毒，没啥
“免费 自由 风险未知 bilibili_NeatVest”是作者加的吧
