### ISSUE TITLE
而你，我的朋友，你是真正的英雄

### ISSUE THREAD

**Issue by GalaxyConvoy** [liusj5257/azurlane_anti_name#24]
而你，我的朋友，你是真正的英雄

**Comment by dark-knifes** [comment]
不要乱开issue好吗

**Comment by GalaxyConvoy** [comment]
我是想表达一下感谢，但刚开始用github，不知道在哪里可以留言

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年4月2日 18:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [liusj5257/azurlane_anti_name] 而你，我的朋友，你是真正的英雄 (Issue #24)


不要乱开issue好吗

―
