### ISSUE TITLE
1.0.1的模块不起作用

### ISSUE THREAD

**Issue by EasyRain** [liusj5257/azurlane_anti_name#25]
真机用的magisk delta 25210版本，最开始的1.0的模块是能用的

**Comment by liusj5257** [comment]
实测真机android13 与雷电9 夜神7 X64都生效

**Comment by EasyRain** [comment]
![Screenshot_2023-04-17-16-36-52-138_io github huskydg magisk](https://user-images.githubusercontent.com/46843500/232431462-574483a4-6af5-4611-ae51-e51da52a25f1.jpg)
![Screenshot_2023-04-17-16-36-55-978_io github huskydg magisk](https://user-images.githubusercontent.com/46843500/232431475-9a8ed572-5953-42b6-8d05-1060535e8a13.jpg)
![Screenshot_2023-04-17-16-37-44-210_com bilibili azurlane](https://user-images.githubusercontent.com/46843500/232431476-5e446885-b5cc-412e-b1a5-069257a6f245.jpg)
官服 红米k40 安卓13

**Comment by liusj5257** [comment]
需要tag 为 perfare 的log才能进一步确认问题,手头没有miui.

**Comment by IA20201** [comment]
> 真机用的magisk delta 25210版本，最开始的1.0的模块是能用的

k50 magiak 官方版26.1是没问题的，会不会是面具版本的问题🤔

**Comment by liusj5257** [comment]
V1.0.3已经修复问题

**Comment by EasyRain** [comment]
> V1.0.3已经修复问题

装了，依旧不生效，又退回1.0了

**Comment by liusj5257** [comment]
> > V1.0.3已经修复问题
> 
> 装了，依旧不生效，又退回1.0了

几个群友是MIUI14 安卓13反馈,重启手机后重启游戏才能生效,至于为什么会这样,只能问小米了
