### ISSUE TITLE
华为渠道服修补后无响应

### ISSUE THREAD

**Issue by dark-knifes** [liusj5257/azurlane_anti_name#3]
如下图
![Screenshot_2023-03-23-18-21-41-975_com bilibili blhx huawei](https://user-images.githubusercontent.com/75507531/227174961-5a5a667f-b296-4933-9609-b8757031e3b5.jpg)

求解决方法或者搓一个可以用的
直连：https://appdl6-drcn.dbankcdn.cn/dl/appdl/application/apk/7e/7e70bd9184a643ddaa4fc6cb9403817c/com.bilibili.blhx.huawei.2211101822.apk

**Comment by dark-knifes** [comment]
这个是我搓好的https://github.com/dark-knifes/azurlinefuckyou/releases/tag/latest

**Comment by liusj5257** [comment]
看了你的日志没问题,可能华为比较特别吧.

**Comment by dark-knifes** [comment]
可是我单独开perseus都不会的，加上这个就不行了

> 看了你的日志没问题,可能华为比较特别吧.
