### ISSUE TITLE
教程1×3的将仓库中libs文件夹中的三个文件夹复制到lib中，是在哪里？

### ISSUE THREAD

**Issue by YanMing1229** [liusj5257/azurlane_anti_name#33]
如题

**Comment by liusj5257** [comment]
[libs文件夹](https://github.com/liusj5257/azurlane_anti_name/tree/master/libs)
教程里这不是蓝色链接么,点击进去不就行了

**Comment by YanMing1229** [comment]
对不起，我傻了

**Comment by duyeguyan** [comment]
没得喷我也找半天，结果这是个超链接要点进去，要不作者加个从这链接吧，新人还以为单纯是个蓝字dT-Tb
