### ISSUE TITLE
立绘和谐问题

### ISSUE THREAD

**Issue by Isharmla** [liusj5257/azurlane_anti_name#34]
该安装包并非完全的反和谐，部分立绘并不是通过true那个代码和谐的，典型代表皇家方舟婚纱，大凤赛车服

**Comment by liusj5257** [comment]
你说的不会是废案包吧,那些资源都已经不存在客户端了,要改自己手动替换

**Comment by Isharmla** [comment]
> 你说的不会是废案包吧,那些资源都已经不存在客户端了,要改自己手动替换

感谢解答，之前一直用的另一个脚本和谐，害我搞错了
