### ISSUE TITLE
lsposed模块无法安装

### ISSUE THREAD

**Issue by Marxel-cn** [liusj5257/azurlane_anti_name#38]
STDERR
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1893241308.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1893241308.tmp/base.apk: Attempt to get length of null array]
错误识别码：1

**Comment by liusj5257** [comment]
NO_CERTIFICATES
apk没签名,自己用mt签名

**Comment by Marxel-cn** [comment]
> NO_CERTIFICATES apk没签名,自己用mt签名

明白了，建议加一句说明
