### ISSUE TITLE
应用端问题

### ISSUE THREAD

**Issue by googgbug** [liusj5257/azurlane_anti_name#41]
请问装官方的安装包和自改的安装包有什么区别呢，因为这个模块我用官方的安装包也能反和谐

**Comment by liusj5257** [comment]
你把我整不会了,模块就是作用于官方包的,他和修改端是两个并行分支.

**Comment by googgbug** [comment]
> 你把我整不会了,模块就是作用于官方包的,他和修改端是两个并行分支.

噢噢，因为我看到上面是写要先卸载官方包再安装修改包，还以为要先装修改包再装模块，不好意思，谢谢回答
