### ISSUE TITLE
关于在使用模块的情况下有时名称反和谐失效的问题

### ISSUE THREAD

**Issue by Cherishhhhh** [liusj5257/azurlane_anti_name#42]
运行环境是真机magisk 安装了lsp 面具版本为25.2 游戏渠道为官方包
不管是单独使用zygisk的模块还是lsp的uncensored模块有时都会出现名称反和谐失效的问题
并且出现问题时游戏在启动到出现健康游戏忠告跳字这段黑屏时间卡很久 模块正常生效就不会出现这个情况

**Comment by liusj5257** [comment]
应该是黑屏卡了10秒吧,代码是每秒尝试打开一次libil2cpp.so,10次都失败log应该会有"libil2cpp.so not found in thread"
![code](https://github.com/liusj5257/azurlane_anti_name/assets/87109954/b66ad279-dce9-40e9-8215-4c66aff51c16)
