### ISSUE TITLE
临时改包完全打不开

### ISSUE THREAD

**Issue by clark1091** [liusj5257/azurlane_anti_name#50]
如题，新包在mumu12完全打不开，直接闪退

**Comment by liusj5257** [comment]
测试mumu12正常

**Comment by 2253** [comment]
我也是直接闪退

**Comment by Jason9269** [comment]
雷电9打不开，闪退能弹出用户协议，卸载全清重装还是这样

**Comment by clark1091** [comment]
无恶意，但是求一份模拟器配置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liusj5257/azurlane_anti_name] 临时改包完全打不开 (Issue #50)




 
测试mumu12正常

**Comment by ericTeufel** [comment]
真机正常运行，mumu12弹出用户协议时闪退，重新安装mumu12依然闪退

**Comment by liusj5257** [comment]
用户协议与渲染引擎有一定关系，弹出来赶紧确认，这版本确实注入不稳定，概率闪退

**Comment by JtVast** [comment]
雷电9模拟器也是，安装完启动游戏还没进检查更新就闪退。

**Comment by 2253** [comment]
我这里是先闪退再弹出用户协议，无解

**Comment by Jason9269** [comment]
> 我这里是先闪退再弹出用户协议，无解

目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9
非常神奇

**Comment by JtVast** [comment]
> > 我这里是先闪退再弹出用户协议，无解
> 
> 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇

好好好，我也成功了！

**Comment by Jason9269** [comment]
> > > 我这里是先闪退再弹出用户协议，无解
> > 
> > 
> > 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇
> 
> 好好好，我也成功了！

俺寻思，只要狂点把用户协议那里过了，之后就不用狂点了，概率进，拼脸就行了

**Comment by LUrenjia114** [comment]
mumu12模拟器覆盖安装上个反和谐版本完全进不去，也没有什么用户协议这东西。。。另外求九游和应用宝版本加速更新感谢

**Comment by YanMing1229** [comment]
雷电九，改完安装打开后闪退但保留用户协议界面
改好的包发给手机就能正常打开
有什么解决办法吗？

**Comment by YanMing1229** [comment]
> > > > 我这里是先闪退再弹出用户协议，无解
> > > 
> > > 
> > > 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇
> > 
> > 
> > 好好好，我也成功了！
> 
> 俺寻思，只要狂点把用户协议那里过了，之后就不用狂点了，概率进，拼脸就行了

我试了下开连点器点不进去

**Comment by YanMing1229** [comment]
还有新发的assetbundle文件夹替换进安装包以后会导致改包文件在真机上卡住
戒指什么的都替换不了

**Comment by longhuangmingtian** [comment]
> > > > 我这里是先闪退再弹出用户协议，无解
> > > 
> > > 
> > > 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇
> > 
> > 
> > 好好好，我也成功了！
> 
> 俺寻思，只要狂点把用户协议那里过了，之后就不用狂点了，概率进，拼脸就行了

神奇的bug，狂点确实概率进游戏了

**Comment by Oscar99999-Chen** [comment]
我也是，我是mumu12直接覆盖安装，然后现在打不开了，没有什么用户协议，只是直接就闪退了。

**Comment by YanMing1229** [comment]
> > > > > 我这里是先闪退再弹出用户协议，无解
> > > > 
> > > > 
> > > > 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇
> > > 
> > > 
> > > 好好好，我也成功了！
> > 
> > 
> > 俺寻思，只要狂点把用户协议那里过了，之后就不用狂点了，概率进，拼脸就行了
> 
> 神奇的bug，狂点确实概率进游戏了

多大概率，好奇，因为我试了几十次一次都没进得去

**Comment by xjd01** [comment]
蓝叠模拟器闪退

**Comment by LFQiwei** [comment]
雷电4和雷电9都在闪退概率进

**Comment by lan23333** [comment]
雷电4和雷电9都是闪退，狂点概率进

**Comment by JtVast** [comment]
> > > > > > 我这里是先闪退再弹出用户协议，无解
> > > > > 
> > > > > 
> > > > > 目前测试在打开客户端之后用鼠标狂点屏幕有概率进去，雷电9 非常神奇
> > > > 
> > > > 
> > > > 好好好，我也成功了！
> > > 
> > > 
> > > 俺寻思，只要狂点把用户协议那里过了，之后就不用狂点了，概率进，拼脸就行了
> > 
> > 
> > 神奇的bug，狂点确实概率进游戏了
> 
> 多大概率，好奇，因为我试了几十次一次都没进得去

左右交替连点空格键比较容易。

**Comment by LUrenjia114** [comment]
什么时候能修复啊，老是用连点撞大运也不是个事啊

**Comment by liusj5257** [comment]
应该已经修复
