### ISSUE TITLE
关于B服的APK的问题

### ISSUE THREAD

**Issue by Oscar99999-Chen** [liusj5257/azurlane_anti_name#54]
之前mumu12覆盖安装无法打开，会直接闪退。
尝试卸载之后再安装依然无法打开，但是在闪退之后会弹出用户协议与隐私政策

**Comment by WKyouka** [comment]
我现在也是这样，但只要不断尝试打开就有概率成功。

**Comment by wbselbf** [comment]
我也是闪退，本来以为用不了了，看到上面的回复就又试了试，重复点了五六次还真进去了，进入游戏后可以正常游玩，这是真的玄学

**Comment by JtVast** [comment]
> 我现在也是这样，但只要不断尝试打开就有概率成功。

刚出新包的时候很容易进，热更新了几次之后就不行了，看到楼主的发言我受到启发，去设置的应用与权限里面把游戏的储存权限开了，好像又能在启动的时候点点点进去了。

**Comment by liusj5257** [comment]
应该修复完成
