### ISSUE TITLE
启用[Enemies]时，游戏有概率会不停加载

### ISSUE THREAD

**Issue by Sonata177** [liusj5257/azurlane_anti_name#57]
[Enemies] enable后，可能会出现以下情况，这个功能拿来练级用的很方便，能修修这个问题吗，谢谢了！

![{99756FB4-48BF-46d8-8DCB-FF16E90487DD}](https://github.com/liusj5257/azurlane_anti_name/assets/147287419/55473e9f-0575-4a93-8156-23dac59c0892)

**Comment by Sonata177** [comment]
闪退也是因为[Enemies] enable=true，之前试了几次不停闪退就给它停了。然后想打14图打不过就enable看看，莫名奇妙的就能用了，然后就出现了图片里面的问题。

**Comment by liusj5257** [comment]
难绷,你的挂不是我改的,谁改的找谁去
