### ISSUE TITLE
这

### ISSUE THREAD

**Issue by E5sixuqi** [liusj5257/azurlane_anti_name#8]
![flase](https://user-images.githubusercontent.com/106328555/227457789-454abced-388f-4303-88d6-4c5c0a8518de.jpg)

**Comment by dark-knifes** [comment]
是不是修改错位置了，按照下面英文版教程试试看

**Comment by dark-knifes** [comment]
可能是我教程写错了去，等pr通过后再试试

**Comment by liusj5257** [comment]
旧教程有问题，各个服务器的插入位置不一定相同
